import { api } from "../services/api.js";
const state = { categories: [], editingId: null };
const $ = (selector) => document.querySelector(selector);
const list = (value) => Array.isArray(value) ? value : value?.content || [];
document.addEventListener("DOMContentLoaded", async () => { bindEvents(); await loadCategories(); });
function bindEvents() { $("#new-category-button")?.addEventListener("click", () => openForm()); $("#close-category-form")?.addEventListener("click", closeForm); $("#cancel-category-form")?.addEventListener("click", closeForm); $("#category-form")?.addEventListener("submit", saveCategory); $("#category-name")?.addEventListener("input", () => { if (!state.editingId) $("#category-slug").value = slugify($("#category-name").value); }); $("#admin-categories-table")?.addEventListener("click", handleAction); }
async function loadCategories() { try { state.categories = list(await api.get("/categories")); render(); } catch (error) { feedback(error.message); } }
function render() { $("#admin-categories-table").innerHTML = state.categories.map((category) => `<tr><td>${category.id}</td><td><strong>${escapeHTML(category.name)}</strong></td><td><code>${escapeHTML(category.slug)}</code></td><td>${actions(category.id)}</td></tr>`).join(""); $("#admin-categories-mobile").innerHTML = state.categories.map((category) => `<article class="admin-mobile-card"><strong>${escapeHTML(category.name)}</strong><span>${escapeHTML(category.slug)}</span><div class="admin-actions">${actions(category.id)}</div></article>`).join(""); }
function actions(id) { return `<button type="button" class="admin-action-button" data-action="edit" data-id="${id}">Editar</button><button type="button" class="admin-action-button danger" data-action="delete" data-id="${id}">Excluir</button>`; }
function handleAction(event) { const button = event.target.closest("[data-action]"); if (!button) return; const id = Number(button.dataset.id); button.dataset.action === "edit" ? openForm(id) : deleteCategory(id); }
function openForm(id = null) { state.editingId = id; $("#category-form").reset(); $("#category-form-message").textContent = ""; const category = state.categories.find((item) => Number(item.id) === id); $("#category-form-title").textContent = id ? "Editar categoria" : "Nova categoria"; if (category) { $("#category-name").value = category.name; $("#category-slug").value = category.slug; } $("#category-form-panel").hidden = false; }
function closeForm() { $("#category-form-panel").hidden = true; state.editingId = null; $("#category-form").reset(); }
async function saveCategory(event) { event.preventDefault(); const payload = { name: $("#category-name").value.trim(), slug: $("#category-slug").value.trim() }; if (!payload.name || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(payload.slug)) { $("#category-form-message").textContent = "Informe nome e slug válido."; return; } try { state.editingId ? await api.put(`/categories/${state.editingId}`, payload) : await api.post("/categories", payload); closeForm(); await loadCategories(); feedback("Categoria salva com sucesso."); } catch (error) { $("#category-form-message").textContent = error.message || "Não foi possível salvar."; } }
async function deleteCategory(id) { const category = state.categories.find((item) => Number(item.id) === id); if (!category || !window.confirm(`Excluir "${category.name}"?`)) return; try { await api.delete(`/categories/${id}`); await loadCategories(); feedback("Categoria excluída."); } catch (error) { feedback(error.message || "Não foi possível excluir."); } }
function slugify(value) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }
function feedback(message) { $("#categories-feedback").textContent = message; }
function escapeHTML(value) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
