import { api } from "../services/api.js";
const state = { orders: [], status: "" };
const $ = (selector) => document.querySelector(selector);
const list = (value) => Array.isArray(value) ? value : value?.content || [];
document.addEventListener("DOMContentLoaded", async () => { $("#order-status-filter")?.addEventListener("change", (event) => { state.status = event.target.value; render(); }); await loadOrders(); });
async function loadOrders() { try { state.orders = list(await api.get("/orders/admin")); render(); } catch (error) { feedback(error.message || "Não foi possível carregar pedidos."); } }
function render() { const orders = state.status ? state.orders.filter((order) => String(order.status).toUpperCase() === state.status) : state.orders; $("#admin-order-count").textContent = `${orders.length} pedido${orders.length === 1 ? "" : "s"}`; $("#admin-orders-list").replaceChildren(...orders.map(createCard)); }
function createCard(order) { const card = document.createElement("article"); card.className = "admin-order-card"; const status = String(order.status || "PENDENTE").toUpperCase(); const items = Array.isArray(order.items) ? order.items : []; card.innerHTML = `<header class="admin-order-header"><div><span class="admin-panel-label">PEDIDO</span><h2>#${escapeHTML(order.id ?? "-")}</h2></div><span class="order-status ${statusClass(status)}">${statusLabel(status)}</span></header><div class="admin-order-meta"><span>${date(order.orderDate || order.createdAt || order.date)}</span><strong>${currency(order.totalAmount ?? order.total)}</strong></div><div class="admin-order-items">${items.map((item) => `<div class="admin-order-item"><span>${escapeHTML(item.productName || item.product?.name || item.name || `Produto #${item.productId || ""}`)} × ${item.quantity}</span><strong>${currency(Number(item.unitPrice ?? item.price ?? 0) * Number(item.quantity || 0))}</strong></div>`).join("") || "<p>Nenhum item disponível.</p>"}</div><footer class="admin-order-actions"><label>Alterar status<select class="admin-select"><option value="PENDENTE">Pendente</option><option value="PAGO">Pago</option><option value="CANCELADO">Cancelado</option></select></label></footer>`; const select = card.querySelector("select"); select.value = status; select.addEventListener("change", () => updateStatus(Number(order.id), select)); return card; }
async function updateStatus(id, select) { const value = select.value; select.disabled = true; try { await api.patch(`/orders/admin/${id}/status`, { status: value }); await loadOrders(); feedback("Status atualizado com sucesso."); } catch (error) { feedback(error.message || "Não foi possível atualizar o pedido."); } finally { select.disabled = false; } }
function statusClass(status) { return { PENDENTE: "status-pending", PAGO: "status-paid", CANCELADO: "status-cancelled" }[status] || "status-pending"; }
function statusLabel(status) { return { PENDENTE: "Pendente", PAGO: "Pago", CANCELADO: "Cancelado" }[status] || status; }
function date(value) { const parsed = new Date(value); return value && !Number.isNaN(parsed.getTime()) ? new Intl.DateTimeFormat("pt-BR").format(parsed) : "Data indisponível"; }
function currency(value) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value) || 0); }
function feedback(message) { $("#orders-feedback").textContent = message; }
function escapeHTML(value) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
